# golangci-lint configuration for Tap
# https://golangci-lint.run/usage/configuration/

run:
  # Timeout for analysis
  timeout: 5m
  # Include test files
  tests: true

linters:
  # Disable all linters by default and enable only the ones we want
  disable-all: true
  enable:
    # Required linters from acceptance criteria
    - govet       # Reports suspicious constructs
    - errcheck    # Checks for unchecked errors
    - staticcheck # Static analysis checks
    - unused      # Checks for unused code
    - gosimple    # Simplifies code
    # Additional useful linters
    - ineffassign # Detects ineffectual assignments
    - typecheck   # Parses and type-checks Go code

linters-settings:
  govet:
    # Enable all analyzers
    enable-all: true
    # Disable shadow checking (can be noisy)
    disable:
      - shadow
  errcheck:
    # Check for errors from type assertions
    check-type-assertions: true
    # Check for errors from blank identifier assignments
    check-blank: false
  staticcheck:
    # Enable all staticcheck analyzers
    checks: ["all"]
  gosimple:
    # Enable all gosimple analyzers
    checks: ["all"]

issues:
  # Maximum issues count per one linter (0 = unlimited)
  max-issues-per-linter: 0
  # Maximum count of issues with the same text (0 = unlimited)
  max-same-issues: 0
  # Skip vendor, third_party, node_modules directories
  exclude-dirs:
    - vendor
    - third_party
    - node_modules
  # Skip generated files
  exclude-files:
    - ".*_generated\\.go$"
  # Exclude some linter messages
  exclude-rules:
    # Exclude some staticcheck messages in test files
    - path: "_test\\.go"
      linters:
        - errcheck
    # Exclude "package comment" warnings
    - linters:
        - staticcheck
      text: "ST1000:"

output:
  # Sort results by file, line, and column
  sort-results: true
  # Print linter name in the end of issue text
  print-linter-name: true
