package themes

import "testing"

// TestTokens_EveryThemeHasRequiredTokens checks that internal/themes/tokens.json
// (generated by frontend/scripts/extract-theme-tokens.mjs) is fresh enough to
// cover every built-in theme with every token the rest of tap depends on.
// This does not shell out to Node or re-derive the file from CSS - the
// byte-for-byte freshness check against theme.css belongs to
// `npm run tokens:check`. This only asserts the shape Go code relies on.
func TestTokens_EveryThemeHasRequiredTokens(t *testing.T) {
	for _, theme := range All() {
		tokens, ok := Tokens(theme.Slug)
		if !ok {
			t.Errorf("theme %q has no tokens.json entry", theme.Slug)
			continue
		}
		for _, required := range RequiredTokens {
			if _, ok := tokens[required]; !ok {
				t.Errorf("theme %q is missing required token %q", theme.Slug, required)
			}
		}
	}
}

func TestTokens_UnknownSlug(t *testing.T) {
	if _, ok := Tokens("does-not-exist"); ok {
		t.Error("Tokens(\"does-not-exist\") returned ok = true, want false")
	}
}

func TestIllustration_EveryThemeHasAllSevenFields(t *testing.T) {
	for _, theme := range All() {
		illustration, ok := Illustration(theme.Slug)
		if !ok {
			t.Errorf("theme %q has no tokens.json entry", theme.Slug)
			continue
		}
		fields := map[string]string{
			"medium":      illustration.Medium,
			"line":        illustration.Line,
			"shapes":      illustration.Shapes,
			"texture":     illustration.Texture,
			"palette_use": illustration.PaletteUse,
			"mood":        illustration.Mood,
			"avoid":       illustration.Avoid,
		}
		for name, value := range fields {
			if value == "" {
				t.Errorf("theme %q has an empty illustration.%s", theme.Slug, name)
			}
		}
	}
}

func TestTokenSlugs_MatchesAll(t *testing.T) {
	tokenSlugs := TokenSlugs()
	all := All()

	if len(tokenSlugs) != len(all) {
		t.Fatalf("TokenSlugs() returned %d entries, All() returned %d", len(tokenSlugs), len(all))
	}
}
